/* DSblock model generated by Dymola from Modelica model RobotC
 Dymola Version 7.0, 2008-02-27 translated this at Tue May 31 19:59:41 2016
 */

#include <matrixop.h>
/* Declaration of C-structs */
/* Prototypes for functions used in model */
#include "Random.c"
int   MyRandom_M(int  fw0_0);
/* Codes used in model */
/* Flattened Modelica model:

function MyRandom
  input Integer fw;
  output Integer res;

external "C" res := Random(fw);
annotation(Include="#include \"Random.c\"");
end MyRandom;
*/



int   MyRandom_M(int  fw0_0) {
  PushContext("MyRandom")
  {
    /* Declare outputs and temporaries */
    int   res0_0;
    res0_0=0;
    /* Start of real code */
    {
      res0_0 = (Random)(fw0_0);
      }
    /* Output section */
    PopContext()
    return res0_0;
  }}
/* DSblock C-code: */

#include <moutil.c>
const char*modelName="RobotC";
const char*usedLibraries[]={0};
const char*default_dymosim_license_filename=0;
#include <dsblock1.c>

/* Define variable names. */

#define Sections_

TranslatedEquations

InitialSection
W_[1] = 3.14159265358979;
W_[4] = 3.14159265358979;
W_[11] = 2;
W_[12] = 4;
W_[13] = 4;
W_[14] = (-2);
W_[15] = (-4);
W_[16] = (-4);
BoundParameterSection
W_[3] = 0.0174532925199433*DP_[10];
W_[6] = 0.0174532925199433*DP_[14];
InitialSection
#ifdef DynSimStruct
W_[0] = 1;
W_[10] = false;
#endif
DefaultSection
InitializeData(0)
InitialSection
Aux_[0] = W_[2];
Aux_[1] = W_[5];
Aux_[2] = W_[17];
InitialSection
InitialSection2
W_[2] = DP_[9];
W_[5] = DP_[13];
InitialSection
Aux_[0] = W_[2];
Aux_[1] = W_[5];
InitialSection2
X_[2] = DP_[2];
X_[0] = DP_[0];
X_[1] = DP_[1];
X_[6] = DP_[8];
X_[5] = DP_[7];
X_[8] = DP_[12];
X_[7] = DP_[11];
W_[17] = Aux_[2];
InitialSection
Init=false;InitializeData(2);Init=true;

OutputSection

DynamicsSection
F_[3] = 0;
F_[2] = X_[3];
W_[0] = PRE(W_[0], 0);
  if (Greater(fabs(X_[0]),"abs(robot.x)", 50,"50", 0)) {
    W_[0] =  -W_[0];
  }
if (NewParameters) {
helpvar[0] = cos(DP_[3]);
}
F_[0] = W_[0]*X_[2]*helpvar[0];
if (NewParameters) {
helpvar[1] = sin(DP_[3]);
}
F_[1] = W_[0]*X_[2]*helpvar[1];
F_[4] = IF GreaterEqual(X_[3],"robot.a", 0,"0", 1) THEN DP_[6]*DP_[4]*DP_[5]*
  fabs(X_[2])+DP_[4]*fabs(X_[3]*X_[2]) ELSE DP_[4]*fabs(X_[3]*X_[2])-DP_[6]*
  DP_[4]*DP_[5]*fabs(X_[2]);
beginwhenBlock
helpvar[2] = fabs(X_[6]);
whenModelicaOld(Greater(helpvar[2],"abs(barrier1.y)", DP_[8],"barrier1.y0", 2), 0) 
  W_[2] = 0;
endwhenModelica()
endwhenBlock
if (NewParameters) {
helpvar[3] = sin(W_[3]);
}
F_[6] = W_[2]*helpvar[3];
if (NewParameters) {
helpvar[4] = cos(W_[3]);
}
F_[5] = W_[2]*helpvar[4];
beginwhenBlock
helpvar[5] = fabs(X_[8]);
whenModelicaOld(Greater(helpvar[5],"abs(barrier2.y)", DP_[12],"barrier2.y0", 3),
   1) 
  W_[5] = 0;
endwhenModelica()
endwhenBlock
if (NewParameters) {
helpvar[6] = sin(W_[6]);
}
F_[8] = W_[5]*helpvar[6];
if (NewParameters) {
helpvar[7] = cos(W_[6]);
}
F_[7] = W_[5]*helpvar[7];

AcceptedSection1
helpvar[8] = X_[0]-X_[5];
helpvar[9] = X_[1]-X_[6];
W_[7] = sqrtGuarded(helpvar[8]*helpvar[8]+helpvar[9]*helpvar[9],"(robot.x-barrier1.x)*(robot.x-barrier1.x)+(robot.y-barrier1.y)*(robot.y-barrier1.y)");
helpvar[10] = X_[0]-X_[7];
helpvar[11] = X_[1]-X_[8];
W_[8] = sqrtGuarded(helpvar[10]*helpvar[10]+helpvar[11]*helpvar[11],
  "(robot.x-barrier2.x)*(robot.x-barrier2.x)+(robot.y-barrier2.y)*(robot.y-barrier2.y)");
W_[9] = RealBmin(W_[7], W_[8]);
beginwhenBlock
whenModelicaOld(Less(W_[9],"dis", 5,"5", 4), 2) 
  W_[17] = (PushModelContext(1,"MyRandom(6)")MyRandom_M(6));
endwhenModelica()
endwhenBlock
PopModelContext();

AcceptedSection2
W_[10] = PRE(W_[10], 1);
  if (Less(W_[9],"dis", 1,"1", 5)) {
    W_[10] = true;
  }
  else{
    W_[10] = false;
  }

DefaultSection
CrossingSection
/* Start of reinit equations */
beginwhenBlock
whenModelicaOld(Less(W_[9],"dis", 5,"5", 4), 3) 
  reinit(X_[3], RealElement( RealTemporaryDense( &W_[11], 1, 6), (SizeType)( 1+
  W_[17] )));
PopAllMarks();
endwhenModelica()
endwhenBlock
beginwhenBlock
whenModelicaOld(Greater(W_[9],"dis", 5,"5", 6), 4) 
  reinit(X_[3], 0);
endwhenModelica()
endwhenBlock
beginwhenBlock
whenModelicaOld(Greater(W_[9],"dis", 5,"5", 6), 5) 
  reinit(X_[2], DP_[2]);
endwhenModelica()
endwhenBlock
/* End of reinit equations */
DefaultSection
InitializeData(1)
EndTranslatedEquations

#include <dsblock6.c>

PreNonAlias(0)
StartNonAlias(0)
DeclareParameter("robot.x0", "", 0, 0, 0.0,0.0,0.0,0,560)
DeclareParameter("robot.y0", "", 1, 0, 0.0,0.0,0.0,0,560)
DeclareParameter("robot.v0", "", 2, 10, 0.0,0.0,0.0,0,560)
DeclareParameter("robot.theta", "", 3, 0, 0.0,0.0,0.0,0,560)
DeclareParameter("robot.m", "[|Kg]", 4, 100, 0.0,0.0,0.0,0,560)
DeclareParameter("robot.g", "", 5, 9.8, 0.0,0.0,0.0,0,560)
DeclareParameter("robot.u", "", 6, 0.05, 0.0,0.0,0.0,0,560)
DeclareState("robot.x", "", 0, 0, 0.0,0.0,0.0,0,544)
DeclareDerivative("robot.der(x)", "", 0, 0.0,0.0,0.0,0,512)
DeclareState("robot.y", "", 1, 0, 0.0,0.0,0.0,0,544)
DeclareDerivative("robot.der(y)", "", 0, 0.0,0.0,0.0,0,512)
DeclareState("robot.v", "", 2, 0, 0.0,0.0,0.0,0,544)
DeclareDerivative("robot.der(v)", "", 0, 0.0,0.0,0.0,0,512)
DeclareState("robot.a", "", 3, 0, 0.0,0.0,0.0,0,560)
DeclareDerivative("robot.der(a)", "", 0, 0.0,0.0,0.0,0,512)
DeclareVariable("robot.dir", "", 1, 0.0,0.0,0.0,0,640)
DeclareState("robot.energy", "[|J]", 4, 0, 0.0,0.0,0.0,0,560)
DeclareDerivative("robot.der(energy)", "", 0, 0.0,0.0,0.0,0,512)
DeclareVariable("barrier1.pi", "", 3.14159265358979, 0.0,0.0,0.0,0,513)
DeclareParameter("barrier1.x0", "", 7, 10, 0.0,0.0,0.0,0,560)
DeclareParameter("barrier1.y0", "", 8, 6, 0.0,0.0,0.0,0,560)
DeclareParameter("barrier1.v0", "", 9, 5, 0.0,0.0,0.0,0,560)
DeclareParameter("barrier1.theta0", "", 10, (-90), 0.0,0.0,0.0,0,560)
DeclareState("barrier1.x", "", 5, 0, 0.0,0.0,0.0,0,544)
DeclareDerivative("barrier1.der(x)", "", 0, 0.0,0.0,0.0,0,512)
DeclareState("barrier1.y", "", 6, 0, 0.0,0.0,0.0,0,544)
DeclareDerivative("barrier1.der(y)", "", 0, 0.0,0.0,0.0,0,512)
DeclareVariable("barrier1.v", "", 0, 0.0,0.0,0.0,0,640)
DeclareVariable("barrier1.theta", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("barrier2.pi", "", 3.14159265358979, 0.0,0.0,0.0,0,513)
DeclareParameter("barrier2.x0", "", 11, 30, 0.0,0.0,0.0,0,560)
DeclareParameter("barrier2.y0", "", 12, 10, 0.0,0.0,0.0,0,560)
DeclareParameter("barrier2.v0", "", 13, 5, 0.0,0.0,0.0,0,560)
DeclareParameter("barrier2.theta0", "", 14, (-90), 0.0,0.0,0.0,0,560)
DeclareState("barrier2.x", "", 7, 0, 0.0,0.0,0.0,0,544)
DeclareDerivative("barrier2.der(x)", "", 0, 0.0,0.0,0.0,0,512)
DeclareState("barrier2.y", "", 8, 0, 0.0,0.0,0.0,0,544)
DeclareDerivative("barrier2.der(y)", "", 0, 0.0,0.0,0.0,0,512)
DeclareVariable("barrier2.v", "", 0, 0.0,0.0,0.0,0,640)
DeclareVariable("barrier2.theta", "", 0, 0.0,0.0,0.0,0,513)
DeclareAlias2("x", "", "robot.x", 1, 1, 0, 0)
DeclareVariable("dis1", "", 0, 0.0,0.0,0.0,0,512)
DeclareVariable("dis2", "", 0, 0.0,0.0,0.0,0,512)
DeclareVariable("dis", "", 0, 0.0,0.0,0.0,0,512)
DeclareVariable("pz", "", false, 0.0,0.0,0.0,0,642)
DeclareVariable("jsd[1]", "", 2, 0.0,0.0,0.0,0,513)
DeclareVariable("jsd[2]", "", 4, 0.0,0.0,0.0,0,513)
DeclareVariable("jsd[3]", "", 4, 0.0,0.0,0.0,0,513)
DeclareVariable("jsd[4]", "", (-2), 0.0,0.0,0.0,0,513)
DeclareVariable("jsd[5]", "", (-4), 0.0,0.0,0.0,0,513)
DeclareVariable("jsd[6]", "", (-4), 0.0,0.0,0.0,0,513)
DeclareVariable("jsdIdx", "", 0, 0.0,0.0,0.0,0,644)
EndNonAlias(0)
#define NX_    9
#define NX2_   0
#define NU_    0
#define NY_    0
#define NW_    18
#define NP_    15
#define NPS_   0
#define NHash1_ 1876978701
#define NHash2_ -1696099600
#define NI_    0
#define NRelF_ 5
#define NRel_  7
#define NTim_  0
#define NSamp_ 0
#define NCons_ 0
#define NA_    1
#define SizePre_ 2
#define SizeEq_ 0
#define SizeDelay_ 0
#define QNLmax_ 0
#define MAXAux 3
#define NrDymolaTimers_ 0
#define NWhen_ 6
#define NCheckIf_ 0
#define NGlobalHelp_ 12
#ifndef NExternalObject_
#define NExternalObject_ 0
#endif

#include <dsblock5.c>

StartDataBlock
StartPreBlock
pre(W_[10],"pz", false, 1);
pre(W_[0],"robot.dir", 1, 0);
EndPreBlock
UpdateQEvaluate(6)
EndDataBlock
